name: skolwa
description: School Management System

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  animated_splash_screen: ^1.1.0
  flutter_svg: ^1.1.5
  google_fonts: ^3.0.1
  firebase_core: ^1.23.0
  firebase_storage: ^10.3.9
  firebase_auth: ^3.10.0
  cloud_firestore: ^3.4.9
  provider: ^6.0.3
  url_strategy: ^0.2.0
  responsive_builder: ^0.4.3

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
     - images/
     - icons/