// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4BP6r2bgvsJZS8PXFs2BONGPLSYy45PY',
    appId: '1:306037179502:web:930a9b2c0a1c81bcb7d27f',
    messagingSenderId: '306037179502',
    projectId: 'sikolwa',
    authDomain: 'sikolwa.firebaseapp.com',
    storageBucket: 'sikolwa.appspot.com',
    measurementId: 'G-BM48YBVTH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBe7mP7xaO6VYq3bSLrJbCSnOIn-0UObRc',
    appId: '1:306037179502:android:0d7ab90b6bdd2f36b7d27f',
    messagingSenderId: '306037179502',
    projectId: 'sikolwa',
    storageBucket: 'sikolwa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvMcWxL9-UZHsAxIDOkmylTHTrg0u4RKA',
    appId: '1:306037179502:ios:b2bfb620ab0c6ce4b7d27f',
    messagingSenderId: '306037179502',
    projectId: 'sikolwa',
    storageBucket: 'sikolwa.appspot.com',
    iosClientId: '306037179502-sf9bjgisjovv55d0h9tiu40l7ndgfecr.apps.googleusercontent.com',
    iosBundleId: 'io.cloutdevelopers.skolwa',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvMcWxL9-UZHsAxIDOkmylTHTrg0u4RKA',
    appId: '1:306037179502:ios:b2bfb620ab0c6ce4b7d27f',
    messagingSenderId: '306037179502',
    projectId: 'sikolwa',
    storageBucket: 'sikolwa.appspot.com',
    iosClientId: '306037179502-sf9bjgisjovv55d0h9tiu40l7ndgfecr.apps.googleusercontent.com',
    iosBundleId: 'io.cloutdevelopers.skolwa',
  );
}
